apiVersion: v1
kind: Namespace
metadata:
  name: platform-verification
  labels:
    app.kubernetes.io/name: platform-verification
    app.kubernetes.io/managed-by: argocd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
